spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3307/products
    username: product
    password: product
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ğŸ” Creates or updates tables automatically
    show-sql: true       # ğŸ§¾ Prints SQL queries to console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # ğŸ§  Important for MySQL 8 compatibility

server:
  port: 1236

keycloak:
  initial:
    jwks:
      url: http://localhost:8080/realms/
  final:
    jwks:
      url: /protocol/openid-connect/certs 